[package]
name = "rust-text-ed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23"
log = "0.4.22"
simple-logging = "2.0.2"
